
commandbus:
  image : rabbitmq:3
  ports:
    - "5672:5672"
#    - "15672:15672"
  expose:
#    - "5672"
    - "15672"
    - "4369"
    - "25672"

publisher:
  image : ondaway/publisher
  ports:
    - "8080:8080"
  environment:
    command_bus: "amqp://guest:guest@commandbus:5672/"
  links:
    - commandbus

